version: '2.4'

services:
  frontend:
    container_name: frontend_production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80

  backend:
    container_name: backend_production
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8080
